products:
  bouncer:
    build:
      environment:
        CGO_ENABLED: "0"
      main-pkg: ./main
      version-var: github.com/palantir/bouncer/cmd.version
      os-archs:
      - os: darwin
        arch: "386"
      - os: darwin
        arch: amd64
      - os: freebsd
        arch: "386"
      - os: freebsd
        arch: amd64
      - os: freebsd
        arch: arm
      - os: linux
        arch: "386"
      - os: linux
        arch: amd64
      - os: linux
        arch: arm
      - os: linux
        arch: arm64
      - os: windows
        arch: "386"
      - os: windows
        arch: amd64
    dist:
      disters:
        type: os-arch-bin
        config:
          os-archs:
          - os: darwin
            arch: "386"
          - os: darwin
            arch: amd64
          - os: freebsd
            arch: "386"
          - os: freebsd
            arch: amd64
          - os: freebsd
            arch: arm
          - os: linux
            arch: "386"
          - os: linux
            arch: amd64
          - os: linux
            arch: arm
          - os: linux
            arch: arm64
          - os: windows
            arch: "386"
          - os: windows
            arch: amd64
    publish: {}
product-defaults:
  publish:
    group-id: com.palantir.bouncer
